const PATEIENT_LOCAL_STRATEGY = 'patient-local';
const PATEIENT_REFRESH_STRATEGY = 'patient-refresh';
const ACCESS_TOKEN_STRATEGY = 'access-token-strategy';
const LOCAL_STRATEGY = 'local-strategy';
const PASSWORD_RESSET_STRATEGY = 'reset-password';
const REFRESH_TOKEN_STRATEGY = 'refresh-token';

export {
  PATEIENT_LOCAL_STRATEGY,
  ACCESS_TOKEN_STRATEGY,
  PATEIENT_REFRESH_STRATEGY,
  LOCAL_STRATEGY,
  PASSWORD_RESSET_STRATEGY,
  REFRESH_TOKEN_STRATEGY,
};
