const AUTH_CONTROLLER = 'auth';
const CITIES_CONTROLLER = 'cities';
const COUNTRIES_CONTROLLER = 'countries';
const DOCTORS_PROFILES_CONTROLLER = 'doctors-profiles';
const PATIENTS_PROFILES_CONTROLLER = 'patients-profiles';
const SPECIALIZATIONS_CONTROLLER = 'specializations';
const CONSULTATIONS_REQUESTS_CONTROLLER = 'consultations-requests';
const PATIENT_HIDDEN_DOCTORS_LIB = 'patient-hidden-doctors-lib';
const DOCTORS_SUGGESTIONS = 'doctors-suggestions';

export {
  AUTH_CONTROLLER,
  CITIES_CONTROLLER,
  COUNTRIES_CONTROLLER,
  DOCTORS_PROFILES_CONTROLLER,
  PATIENTS_PROFILES_CONTROLLER,
  SPECIALIZATIONS_CONTROLLER,
  CONSULTATIONS_REQUESTS_CONTROLLER,
  PATIENT_HIDDEN_DOCTORS_LIB,
  DOCTORS_SUGGESTIONS,
};
